### PR TITLE
Migration for Activity.subproject field

### PR DESCRIPTION
**Pull request by daveeloo**
-Migration so subproject=package+version and type="package_upload"
-Delete fields package and version and their unique constraint

### CODE REVIEW

**Comment by paulproteus** [comment]
My current suggestion is, by the power of YAGNI, simply drop the version number from the entire app. If we need it back, we can get it from UDD after all. I'm convinceable, though.

**Comment by paulproteus** [comment]
Interesting; didn't see your comment when I left mine.

Your approach does mean that if there are two packages, one called alpine and other called alpine-pgp-filters (or whatever), then you can't handle alpine-pgp-filters.

Remind me, what do we want to achieve by keeping the version data in there?

**Comment by paulproteus** [comment]
(hack that would work for your strategy: query for "alpine " (note trailing space) rather than "alpine". But that does seem kind of messy.)

**Comment by paulproteus** [comment]
We want the version data just to improve the quality of that one page, right? So IMHO leave the version data of this pull request, and then create a new pull request with the version migration etc. where it also affects that page.

**Comment by daveeloo** [comment]
The only problem with dropping the version number is that recovering it would mean dropping the whole database and reimporting since this information isn't saved anywhere in the 'default' database, only in the 'udd' database. That really isn't that big of a deal. The other issue is the table on the personal page that shows what packages the person uploaded also shows the version next to it. I don't know how important that is.

**Comment by paulproteus** [comment]
Fair enough. I guess what I'm saying is, if you want the version data, don't (remove the column and compress it down into a string with some other data).

**Pull request merged**
